version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: unless-stopped
