version: "3.9"

services:
  backend:
    build:
      context: ../../../Server   # adjust path
      # This path is from the above context : ../../../Server
      dockerfile: ../DevOps/01.Build/Production/backend.Dockerfile 
    container_name: backend
    networks:
      - mern-network
    env_file:
      - ../../../Server/.env
    ports:
      - "3000:3000"   # expose to host (optional)
    restart: unless-stopped

  frontend:
    build:
      context: ../../../Client    # adjust path
      # This path is from the above context : ../../../Client
      dockerfile: ../DevOps/01.Build/Production/frontend.Dockerfile
    container_name: frontend
    networks:
      - mern-network
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

networks:
  mern-network:
    driver: bridge
