# docker-compose.yml
version: "3.9"

services:
  backend:
    build:
      context: ../../../Server   # path to your backend folder
      dockerfile: Dockerfile
    container_name: backend.Dockerfile
    ports:
      - "5000:5000"
    networks:
      - mern-network

  frontend:
    build:
      context: ../../../Client   # path to your frontend folder
      dockerfile: Dockerfile
    container_name: frontend.Dockerfile
    ports:
      - "5173:5173"
    networks:
      - mern-network
    depends_on:
      - backend

networks:
  mern-network:
    driver: bridge
