global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "backend"
    static_configs:
      - targets: ["backend:3000"]

  - job_name: "frontend"
    static_configs:
      - targets: ["frontend:80"]
